# Add nodes registered with blue load balancer to live load balancer
- name: Add BLUE nodes to GREEN Load balancer
  local_action:
    module: rax_clb_nodes
    credentials: "{{ creds_servers_path }}"
    load_balancer_id: "{{ workshop_green_load_balancer.balancer.id }}"
    address: "{{ item.address }}"
    port: "{{ server_port }}" 
    condition: enabled
    type: primary
    wait: yes
    wait_timeout: 180
    region: "{{ region }}"
  with_items: workshop_blue_load_balancer.balancer.nodes
  tags:
    - blue-to-green

# Drain nodes from raxio green load balancer
- name: drain the node
  local_action:
    module: rax_clb_nodes
    credentials: "{{ creds_servers_path }}"
    load_balancer_id: "{{ workshop_green_load_balancer.balancer.id }}"
    node_id: "{{ item.id }}"
    condition: draining 
    wait: true
    wait_timeout: 180
    region: "{{ region }}"
  with_items: workshop_green_load_balancer.balancer.nodes
  tags:
    - blue-to-green

# place holder task to wait for connections to clear
- name: wait for app connections to close
  command: echo "true"
  register: connections
  until: connections.stdout == "true"
  retries: 20
  delay: 10
  tags:
    - blue-to-green

- name: disable the node
  local_action:
    module: rax_clb_nodes
    credentials: "{{ creds_servers_path }}"
    load_balancer_id: "{{ workshop_green_load_balancer.balancer.id }}"
    node_id: "{{ item.id }}"
    condition: disabled
    wait: true
    wait_timeout: 180
    region: "{{ region }}"
  with_items: workshop_green_load_balancer.balancer.nodes
  tags:
    - blue-to-green

- name: remove the node
  local_action:
    module: rax_clb_nodes
    credentials: "{{ creds_servers_path }}"
    load_balancer_id: "{{ workshop_green_load_balancer.balancer.id }}"
    node_id: "{{ item.id }}"
    condition: disabled
    wait: true
    state: absent
    wait_timeout: 180
    region: "{{ region }}"
  with_items: workshop_green_load_balancer.balancer.nodes
  tags:
    - blue-to-green

- name: Add GREEN nodes to BLUE Load balancer
  local_action:
    module: rax_clb_nodes
    credentials: "{{ creds_servers_path }}"
    load_balancer_id: "{{ workshop_blue_load_balancer.balancer.id }}"
    address: "{{ item.address }}"
    port: "{{ server_port }}" 
    condition: enabled
    type: primary
    wait: yes
    wait_timeout: 180
    region: "{{ region }}"
  with_items: workshop_green_load_balancer.balancer.nodes
  tags:
    - blue-to-green

