---
- hosts: localhost
  connection: local
  gather_facts: True
  vars:
    - files:
        /root/.ssh/authorized_keys: /var/lib/jenkins/.ssh/id_rsa.pub
  roles:
     - load_balancer
     - cloud_servers

- hosts: workshop
  gather_facts: True 
  roles: 
     - deploy

- hosts: localhost
  connection: local
  gather_facts: True
  roles:
     - drain
     - test
     - clean_up
