---
- hosts: localhost
  connection: local
  gather_facts: True
  roles:
     - load_balancer
     - cloud_servers

- hosts: workshop
  gather_facts: True 
  roles: 
     - deploy

- hosts: localhost
  connection: local
  gather_facts: True
  roles:
     - drain
     - test
     - clean_up
